### ISSUE TITLE
Bug report: ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by stephanecollot** [opt-nc/yamlfixer#83]
Hi

With Python 3.8, after installing current version I get:
```
 $ yamlfixer conf/
Traceback (most recent call last):
  File "/Users//miniconda3/envs/py38/bin/yamlfixer", line 5, in <module>
    from yamlfixer.__main__ import run
  File "/Users//miniconda3/envs/py38/lib/python3.8/site-packages/yamlfixer/__main__.py", line 24, in <module>
    from .yamlfixer import YAMLFixer
  File "/Users//miniconda3/envs/py38/lib/python3.8/site-packages/yamlfixer/yamlfixer.py", line 25, in <module>
    from .filefixer import FileFixer
  File "/Users//miniconda3/envs/py38/lib/python3.8/site-packages/yamlfixer/filefixer.py", line 23, in <module>
    import magic
  File "/Users//miniconda3/envs/py38/lib/python3.8/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "/Users//miniconda3/envs/py38/lib/python3.8/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by adriens** [comment]
Fixed in https://github.com/opt-nc/yamlfixer/releases/tag/0.5.0

**Comment by stephanecollot** [comment]
Thank you, fyi I'm was on Mac.

**Comment by adriens** [comment]
Hi guys @stephanecollot  @tamere-allo-peter  : do you think  #64 could have allowed us to avoid that issue... or a `brew` based package ?

**Comment by stephanecollot** [comment]
Hi, I don't know, I never heard about pipx so far.

**Comment by tamere-allo-peter** [comment]
@adriens : I don't think so, but anyway this library is not needed anymore.
